name: Atualizar Notícias MidasVIP

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write # Permissão necessária para o bot salvar o arquivo no seu repositório

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install requests googletrans==4.0.0-rc1

      - name: Rodar Robô de Notícias
        run: python robô_noticias.py

      - name: Fazer Commit e Push do cache
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add noticias_cache.json
          # O comando abaixo verifica se houve mudança antes de tentar fazer o commit
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automacao: Atualizando noticias_cache.json" && git push)
